spring:
  main:
    banner-mode: off
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    ignore-missing-migrations: true
  jackson:
    date-format: dd.MM.yyyy
server:
  port: 8080